---
- hosts: all
  tasks:
    - name: firewalld is disabled
      systemd: name=firewalld enabled=no state=stopped

    - name: install extra packages
      yum:
        name:
          - jq
        state: latest
        update_cache: true

- hosts: es1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "es1"
      discovery.seed_hosts: 
        - "es1:9300"
        - "es2:9300"
        - "es3:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: false
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: es2 es3
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "es1"
      discovery.seed_hosts:
        - "es1:9300"
        - "es2:9300"
        - "es3:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

